Repository devsargam/SnakeGame, pull requests merged in 2022-10, with the labels that each got.

#4 Hactoberfest 2022
  README.md
Labels: documentation, hacktoberfest-accepted

#7 Handle Game Over and restart
  index.html
  js/script.js
Labels: enhancement, hacktoberfest-accepted

#10 Best score is saved to local storage
  js/script.js
Labels: enhancement, hacktoberfest-accepted

#11 Add audio turn on/off button
  assets/pictures/audioOff.png
  assets/pictures/audioOn.png
  css/styles.css
  index.html
  js/script.js
Labels: enhancement, hacktoberfest-accepted

#27 add splash title screen
  assets/audio/buttonClick.mp3
  package.json
  src/css/styles.css
  src/index.html
  src/scripts/index.js
  yarn.lock
Labels: enhancement, hacktoberfest-accepted

#40 Corrected the guide in the readme file
  README.md
Labels: documentation, hacktoberfest-accepted

#50 Improved Overlay Interface
  src/css/styles.css
  src/index.html
  src/scripts/classes/betterboard.js
  src/scripts/difficulty.js
Labels: enhancement, hacktoberfest-accepted, design

#56 Added instruction on "How to Play"
  src/css/styles.css
  src/index.html
  src/scripts/classes/betterboard.js
Labels: documentation, enhancement, hacktoberfest-accepted, hacktoberfest

#51 Added Game Over modal functionality
  package-lock.json
  src/css/styles.css
  src/index.html
  src/scripts/classes/betterboard.js
  yarn.lock
Labels: hacktoberfest-accepted, design

#49 Fix Score-Issue
  src/css/styles.css
Labels: hacktoberfest-accepted, design

#60 Fix Capitalization & Add More Themes
  package-lock.json
  src/scripts/classes/betterboard.js
  src/scripts/difficulty.js
  src/scripts/themes.js
Labels: enhancement, hacktoberfest-accepted, hacktoberfest, design
